name: push to path a file
on:
  schedule:
    - cron: '*/15 0-1 * * *'
  push:
    branches:    
      - 'main'
    paths:
      - 'file/**'
jobs:
  do-it:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo "Hello World"

  Dev:
    name: 'Terraform Dev'
    needs: [do-it]
    uses: Zia-Eurus/terraform-gcp-github-actions/.github/workflows/reusable-workflow.yaml@main
    with:
      directory_path: ./infra
      environment: 'dev'