name: push to path a file
on:
  schedule:
    - cron: '*/15 0-1 * * *'
  push:
    branches:    
      - 'main'
    paths:
      - 'file/**'
jobs:
  do-it:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo "Hello World"