name: Reusable work flow

on:
  workflow_call:
    inputs:
      directory_path:
        required: false
        type: string
        default: './infra'
      environment:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      directory_path:
        required: true
        type: string
        description: 'Directory on which terraform execute'
      environment:
        required: true
        type: choice
        description: 'Environment name (dev/prod)'
        options:
        - dev
        - prod
        - all 

concurrency: 
  group: ${{ inputs.environment || github.event.inputs.environment }}-${{ github.head_ref || github.ref }}
permissions:
  contents: 'read'
  id-token: 'write'
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment || github.event.inputs.environment }}
    env:
      head_ref: ${{ github.head_ref || github.ref }}
      directory_path: ${{ inputs.directory_path || github.event.inputs.directory_path }}
      environment: ${{ inputs.environment || github.event.inputs.environment }}
      PROJECT_ID: "eurus-project-dev"
      PROJECT_NUMBER: "103365112501"
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: echo env variables
      run: |
        echo $head_ref
        echo $directory_path
        echo $environment

    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
  
    - id: 'auth'
      name: Google Auth
      uses: google-github-actions/auth@v0.4.0
      with:
        workload_identity_provider: 'projects/${{env.PROJECT_NUMBER}}/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
        service_account: '${{env.PROJECT_NUMBER}}-compute@developer.gserviceaccount.com'
        project_id: ${{env.PROJECT_ID}}

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      working-directory: ${{env.directory_path}}
      run: |
        pwd
        gcloud version
        terraform init

    - name: Terraform Format
      working-directory: ${{env.directory_path}}
      run: |
        pwd
        terraform fmt -check

    - name: Terraform Plan
      working-directory: ${{env.directory_path}}
      run: |
        pwd
        terraform plan -lock=false

      # On push to main, build or change infrastructure according to Terraform configuration files
      # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
    - name: Terraform Apply
      working-directory: ${{env.directory_path}}
      if: github.ref == 'refs/heads/main' # && github.event_name == 'push'
      run: |
        pwd
        terraform apply -auto-approve -lock=false
